spring.application.name=high-performance-consumer
server.port=9090

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092,localhost:9093

# Topic Configuration
kafka.performance.topic=performance.topic
kafka.ordered.topic=ordered.topic
kafka.request.topic=request.topic
kafka.reply.topic=reply.topic

# Logging
logging.level.com.hunglp.consumer=INFO
logging.level.org.springframework.kafka=WARN
logging.level.org.apache.kafka=WARN
