spring:
  application:
    name: high-performance-producer
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093

server:
  port: 8080

logging:
  level:
    com.hunglp.producer: INFO
    org.springframework.kafka: WARN
    org.apache.kafka: WARN

kafka:
  reply:
    topic: reply.topic
